// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pos.DataAccess.Data;

#nullable disable

namespace Pos.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240617132743_SeedCateoryTableData")]
    partial class SeedCateoryTableData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pos_backend.Models.Category", b =>
                {
                    b.Property<string>("CategoryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameKO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryCode");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryCode = "201",
                            DeptCode = "1",
                            Id = 1,
                            NameEN = "Eggplant",
                            NameKO = "가지류"
                        },
                        new
                        {
                            CategoryCode = "202",
                            DeptCode = "1",
                            Id = 1,
                            NameEN = "Potato",
                            NameKO = "감자류"
                        },
                        new
                        {
                            CategoryCode = "203",
                            DeptCode = "1",
                            Id = 1,
                            NameEN = "Sweet Potato",
                            NameKO = "고구마류"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
