// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pos.DataAccess.Data;

#nullable disable

namespace Pos.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240619173729_AddImageUrlToItem")]
    partial class AddImageUrlToItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pos.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameKO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryCode = "201",
                            DeptCode = "1",
                            NameEN = "Eggplant",
                            NameKO = "가지류"
                        },
                        new
                        {
                            Id = 2,
                            CategoryCode = "202",
                            DeptCode = "1",
                            NameEN = "Potato",
                            NameKO = "감자류"
                        },
                        new
                        {
                            Id = 3,
                            CategoryCode = "203",
                            DeptCode = "1",
                            NameEN = "Sweet Potato",
                            NameKO = "고구마류"
                        });
                });

            modelBuilder.Entity("Pos.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameKO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeptCode = "1",
                            NameEN = "Produce",
                            NameKO = "청과"
                        },
                        new
                        {
                            Id = 2,
                            DeptCode = "2",
                            NameEN = "Fish",
                            NameKO = "수산"
                        },
                        new
                        {
                            Id = 3,
                            DeptCode = "3",
                            NameEN = "Meat",
                            NameKO = "정육"
                        },
                        new
                        {
                            Id = 4,
                            DeptCode = "4",
                            NameEN = "Deli",
                            NameKO = "델리"
                        },
                        new
                        {
                            Id = 5,
                            DeptCode = "5",
                            NameEN = "Houseware",
                            NameKO = "하우스웨어"
                        },
                        new
                        {
                            Id = 6,
                            DeptCode = "6",
                            NameEN = "Grocery",
                            NameKO = "그로서리"
                        });
                });

            modelBuilder.Entity("Pos.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeptCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameKO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryCode = "201",
                            DeptCode = "1",
                            ItemCode = "12010001",
                            NameEN = "Korean Eggplant",
                            NameKO = "한국 가지"
                        },
                        new
                        {
                            Id = 2,
                            CategoryCode = "201",
                            DeptCode = "1",
                            ItemCode = "12010002",
                            NameEN = "American Eggplant",
                            NameKO = "미국 가지"
                        },
                        new
                        {
                            Id = 3,
                            CategoryCode = "202",
                            DeptCode = "1",
                            ItemCode = "12020003",
                            NameEN = "Idaho Potato",
                            NameKO = "아이다호 감자"
                        },
                        new
                        {
                            Id = 4,
                            CategoryCode = "203",
                            DeptCode = "1",
                            ItemCode = "12020004",
                            NameEN = "Korean Sweet Potato",
                            NameKO = "한국 고구마"
                        },
                        new
                        {
                            Id = 5,
                            CategoryCode = "203",
                            DeptCode = "1",
                            ItemCode = "12020005",
                            NameEN = "American Sweet Potato",
                            NameKO = "미국 고구마"
                        });
                });

            modelBuilder.Entity("Pos.Models.Item", b =>
                {
                    b.HasOne("Pos.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryCode")
                        .HasPrincipalKey("CategoryCode");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
